Feat/hash consensus tests
lidofinance/core pull request #120
Opened 2024-07-03 19:39 UTC by eddort

2024-07-15 10:36 UTC, tamtamchik commented on test/0.8.9/oracle/hashConsensus.accessControl.test.ts
> +  const manageMembersAndQuorumRoleKeccak256 = keccak256(toUtf8Bytes("MANAGE_MEMBERS_AND_QUORUM_ROLE"));
We have `streccak` exactly for this in `lib`

2024-07-15 14:06 UTC, tamtamchik commented on test/0.8.9/oracle/hashConsensus.accessControl.test.ts
> +    const DEFAULT_ADMIN_ROLE = ZERO_HASH;
We have DEFAULT_ADMIN_ROLE in constants

2024-07-15 14:09 UTC, tamtamchik commented on test/0.8.9/oracle/hashConsensus.accessControl.test.ts
> +        await expect(consensus.connect(account1).updateInitialEpoch(10)).to.be.revertedWith(
We have `revertedWithOZAccessControlError` assertion added to chai, will simplify code a bit:
Example: https://github.com/lidofinance/core/blob/e6ec096b77bb86b0d7d626668ce93689f2360583/test/0.8.9/oracle/baseOracle.accessControl.test.ts#L53-L53

2024-07-15 14:12 UTC, tamtamchik commented on test/0.8.9/oracle/hashConsensus.accessControl.test.ts
> +      snapshot = await deploy({ initialEpoch: null });
Do we need to redeploy before each test? Would deploy in the `before` block saving the snapshot and then just resetting `afterEach` test works?

2024-07-15 14:14 UTC, tamtamchik commented on test/0.8.9/oracle/hashConsensus.accessControl.test.ts
> +      snapshot = await deploy({ initialEpoch: null });
I see that deploy is special in this case, but other contexts could benefit from using caches while testing and avoid deploying before every test

2024-07-15 14:36 UTC, tamtamchik approved these changes
This is huuuuuuuge! 🙌 Looks great! 
I just left some nonblocking comments and suggestions.

2024-07-15 14:36 UTC, tamtamchik commented on test/0.8.9/oracle/hashConsensus.fastLaneLength.test.ts
> +  context("method setFastLaneLengthSlots", () => {
```suggestion
  context("setFastLaneLengthSlots", () => {
```

2024-07-15 14:36 UTC, tamtamchik commented on test/0.8.9/oracle/hashConsensus.happyPath.test.ts
> +describe("HashConsensus:happyPath", function () {
This is basically integration test, not unit test, am I right?

2024-07-15 14:36 UTC, tamtamchik commented on test/0.8.9/oracle/hashConsensus.members.test.ts
> +      it("scenario 1", async () => {
Not an informative name. Is this an integration test? 
Same for next tests

2024-07-19 13:09 UTC, tamtamchik commented
Updated PR to target the `repovation` branch.

2024-07-19 15:35 UTC, TheDZhon requested changes
Thank you for the unstoppable effort! :heart: 

I suggest addressing @tamtamchik and my comments to make it merged.

2024-07-19 15:35 UTC, TheDZhon commented on test/0.8.9/oracle/hashConsensus.accessControl.test.ts
> +  let admin: Signer;
Should we use `Signer` or `HardhatSigner` here and there for consistency? :thinking: 
cc: @mymphe @tamtamchik

2024-07-19 15:35 UTC, TheDZhon commented on test/0.8.9/oracle/hashConsensus.accessControl.test.ts
> +    const mockReportProcessorFactory = await ethers.getContractFactory("MockReportProcessor");
maybe use typechain-generated factories? :thinking:

2024-07-19 15:35 UTC, TheDZhon commented on test/0.8.9/oracle/hashConsensus.accessControl.test.ts
> +      snapshot = await deploy({ initialEpoch: null });
Should the initial epoch be an integral value instead of `null`?

2024-07-19 15:35 UTC, TheDZhon commented on test/0.8.9/oracle/hashConsensus.fastLaneMembers.test.ts
> +describe("HashConsensus:Fast-lane members", () => {
```suggestion
describe("HashConsensus:Fastlane members", () => {
```

2024-07-19 15:35 UTC, TheDZhon commented on test/0.8.9/oracle/hashConsensus.fastLaneMembers.test.ts
> +    stranger: Signer;
```suggestion
  let admin: Signer;
  let member1: Signer;
  let member2: Signer;
  let member3: Signer;
  let member4: Signer;
  let member5: Signer;
  let stranger: Signer;
```

(just for consistency)

2024-07-19 15:35 UTC, TheDZhon commented on test/0.8.9/oracle/hashConsensus.happyPath.test.ts
> +describe("HashConsensus:happyPath", function () {
it's more like a scenario test, though, not the integration still

2024-07-19 15:35 UTC, TheDZhon commented on test/0.8.9/oracle/hashConsensus.members.test.ts
> +      it("scenario 1", async () => {
agree, better provide an explanation here

2024-07-19 15:35 UTC, TheDZhon commented on test/deploy/hashConsensus.ts
> +  reportProcessor?: MockReportProcessor | null | undefined;
why do we need null?

2024-07-22 19:22 UTC, eddort commented on test/0.8.9/oracle/hashConsensus.accessControl.test.ts
> +    const mockReportProcessorFactory = await ethers.getContractFactory("MockReportProcessor");
fixed

2024-07-22 19:23 UTC, eddort commented on test/deploy/hashConsensus.ts
> +  reportProcessor?: MockReportProcessor | null | undefined;
this method was not moved by me, I just reused it
I rewrote the types now null is not used there

2024-07-22 19:27 UTC, eddort commented on test/0.8.9/oracle/hashConsensus.accessControl.test.ts
> +      snapshot = await deploy({ initialEpoch: null });
I've corrected all the points you mentioned

2024-07-22 19:27 UTC, eddort commented on test/0.8.9/oracle/hashConsensus.accessControl.test.ts
> +        await expect(consensus.connect(account1).updateInitialEpoch(10)).to.be.revertedWith(
fixed

2024-07-22 19:28 UTC, eddort commented on test/0.8.9/oracle/hashConsensus.accessControl.test.ts
> +    const DEFAULT_ADMIN_ROLE = ZERO_HASH;
fixed

2024-07-22 19:28 UTC, eddort commented on test/0.8.9/oracle/hashConsensus.accessControl.test.ts
> +  const manageMembersAndQuorumRoleKeccak256 = keccak256(toUtf8Bytes("MANAGE_MEMBERS_AND_QUORUM_ROLE"));
fixed

2024-07-22 19:52 UTC, eddort commented on test/0.8.9/oracle/hashConsensus.members.test.ts
> +      it("scenario 1", async () => {
fixed

2024-07-23 09:29 UTC, tamtamchik commented on test/0.8.9/oracle/hashConsensus.happyPath.test.ts
> +describe("HashConsensus:happyPath", function () {
Agree. No need to change anything here.

2024-07-23 09:39 UTC, tamtamchik commented on test/0.8.9/oracle/hashConsensus.accessControl.test.ts
> +  let admin: Signer;
`HardhatEthersSigner` is just an implementation of the Signer interface. We mostly use `HardhatEthersSigner` in tests, but I don't see the downsides of using the Signer interface here. I'm not sure if this even matters, to be honest

2024-07-23 09:44 UTC, tamtamchik commented on test/0.8.9/oracle/hashConsensus.accessControl.test.ts
> +    const mockReportProcessorFactory = await ethers.getContractFactory("MockReportProcessor");
It could be even simpler to use `await ethers.deployContract("ContractName")` it uses a corresponding factory under the hood, reduces contract deployment to just 1 call, and saves some lines of code :) 

But! This is not an issue; we could skip this for later for reRepovation :) this is just a `hint`

2024-07-23 10:22 UTC, merged