Proposed fixes for MixBytes audit
lidofinance/core pull request #121
Opened 2024-07-04 10:06 UTC by vp4242

2024-07-04 13:06 UTC, TheDZhon requested changes
:eyes:

2024-07-04 13:06 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
>      error IncorrectAppearedValidators(uint256 churnLimit);
```suggestion
    error IncorrectAppearedValidators(uint256 churnLimit, uint256 actualAppearedValidators);
```

2024-07-04 13:11 UTC, TheDZhon approved these changes
LGTM

2024-07-05 09:21 UTC, folkyatina approved these changes
:shipit:

2024-07-09 06:59 UTC, avsetsin approved these changes
lgtm

2024-07-09 08:15 UTC, merged