add a SECURITY notice
lidofinance/core pull request #147
Opened 2024-08-12 13:08 UTC by mymphe

This PR adds a SECURITY.md file which refers users to Immunefi

2024-08-16 07:46 UTC, TheDZhon requested changes
Love it!

Though please tune up wording a bit

2024-08-16 07:46 UTC, TheDZhon commented on SECURITY.md
> +The Lido team appreciates your efforts to responsibly disclose your findings and will make every effort to acknowledge your contributions.
No 'Lido team' please :)

Lido contributors :pray:

2024-08-20 11:22 UTC, tamtamchik commented on SECURITY.md
> +Please DO NOT file a public issue on GitHub or disclose the vulnerability publicly in any way before it has been addressed by the Lido core contributors.
```suggestion
> [!IMPORTANT]
> Please DO NOT file a public issue on GitHub or disclose the vulnerability publicly in any way before it has been addressed by the Lido core contributors.
```

2024-08-20 11:23 UTC, tamtamchik commented on SECURITY.md
> +2. The Lido team will assess the report and may ask for additional information or clarification.
```suggestion
2. The Lido contributors will evaluate your report and may request additional information or clarification.
```

2024-08-20 11:25 UTC, tamtamchik commented on SECURITY.md
> +4. After the fix has been deployed, the team will publish a security advisory and acknowledge your contribution (if you wish to be credited).
```suggestion
4. After the fix is deployed, a security advisory will be published, and your contribution will be acknowledged (if you wish to be credited).
```

2024-08-20 14:01 UTC, TheDZhon approved these changes
LGTM

2024-08-20 14:01 UTC, merged