Add Issue forms
lidofinance/core pull request #148
Opened 2024-08-12 13:10 UTC by mymphe

This PR add issue forms to the repo

2024-08-16 07:43 UTC, TheDZhon approved these changes
:heart:

2024-08-16 07:45 UTC, TheDZhon requested changes

2024-08-16 07:45 UTC, TheDZhon commented on .github/ISSUE_TEMPLATE/CONTRACT-BUG-REPORT.yml
> +description: File a bug report in a contract.
Should refer to the SECURITY page first :warning: 

Reason: to file a bug by 3rd-party via Immunefi

2024-08-26 16:14 UTC, tamtamchik commented on .github/ISSUE_TEMPLATE/CONTRACT-BUG-REPORT.yml
> +description: File a bug report in a contract.
It looks like it is impossible to add a link to the GitHub issue reporting interface. Documentation refers

<img width="1250" alt="Screenshot 2024-08-26 at 17 11 31" src="https://github.com/user-attachments/assets/c7aef2c2-c530-4505-8733-8ad7c642b8dd">

2024-08-26 16:39 UTC, tamtamchik commented
Using just a single text box is way easier than filling out an entire form. It lets users think less, saves time, and they can just write what they need. I really think simplicity is the way to go for reporting. But throwing in some markdown guidance could be helpful to keep the report on point and not just a random ramble.

2024-09-02 10:54 UTC, tamtamchik approved these changes

2024-09-02 12:41 UTC, TheDZhon approved these changes
Let the sunshine in

2024-09-02 13:01 UTC, merged