Repovation weekly PR
lidofinance/core pull request #188
Opened 2024-09-02 14:58 UTC by tamtamchik

Updates related to Lido core repository "repovation". Shipped to master weekly.

2024-09-05 19:40 UTC, tamtamchik commented
@lidofinance/review-gh-workflows sorry for the size of the PR, but here only 2 files with minor changes, don't think it'll take too long to review.

2024-09-05 23:33 UTC, rnmsslido commented
LGTM for the changes in `.github/workflows`. Not reviewing other parts of the PR as they are outside the scope of `review-gh-workflows` group.

2024-09-05 23:39 UTC, rnmsslido approved these changes

2024-09-09 08:46 UTC, mymphe approved these changes

2024-09-09 20:11 UTC, TheDZhon requested changes
What a titanic work made here :fire: 

I asked a few questions here and there; please consider them favorably with an attitude to make the solution more future-proof :+1:

2024-09-10 11:20 UTC, tamtamchik reviewed
Thank you for your feedback! ❤️  
I have addressed some of the raised issues in PR #207 / added my comments to continue the discussion here.

2024-09-10 11:20 UTC, tamtamchik commented on scripts/dao-upgrade.sh
I think we can, but I would prefer to create a separate task for this along with the refactoring of the deployment steps.

2024-09-10 16:56 UTC, TheDZhon approved these changes
Gotta be big :muscle:

2024-09-10 17:02 UTC, merged