Add sepolia deposit adapter
lidofinance/core pull request #198
Opened 2024-09-04 12:05 UTC by vp4242

Add sepolia deposit adapter

## Context

Deposits on Sepolia works a bit differently than on Mainnet.

## Problem

For Lido protocol to work, the deposit adapter for Sepolia is needed.

## Solution

Sepolia deposit adapter implementation + tests

2024-09-04 16:17 UTC, tamtamchik commented
@vp4242, I would suggest pushing this contract to the `master` branch via the `renovation` branch (#188). Having this contract only in the `develop` branch will greatly decrease transparency.

2024-09-05 17:33 UTC, TheDZhon requested changes
:+1: Little did I suggest with this review

2024-09-05 17:33 UTC, TheDZhon commented on contracts/testnets/sepolia/SepoliaDepositAdapter.sol
> +        ISepoliaDepositContract(0x7f02C3E3c98b133055B8B348B2Ac625669Ed295D);
it was `immutable` before, why change tho?

2024-09-05 17:33 UTC, TheDZhon commented on contracts/testnets/sepolia/SepoliaDepositAdapter.sol
> +        ISepoliaDepositContract(0x7f02C3E3c98b133055B8B348B2Ac625669Ed295D);
I mean we can have it passed via ctor with no worries since immutables are part of the bytecode, not storage

2024-09-05 17:33 UTC, TheDZhon commented on contracts/testnets/sepolia/SepoliaDepositAdapter.sol
> +            _transferOwnership(msg.sender);
I'd suggest passing an argument about who should be the owner (not just `msg.sender`)

2024-09-05 17:36 UTC, TheDZhon commented on contracts/testnets/sepolia/SepoliaDepositAdapter.sol
> +contract SepoliaDepositAdapter is IDepositContract, Ownable {
Let's follow [LIP-10](https://github.com/lidofinance/lido-improvement-proposals/blob/develop/LIPS/lip-10.md)

i.e.:
- derive from `Versioned`
- use `_initializeContractVersionTo(1)`

Reference: https://github.com/lidofinance/core/blob/master/contracts/0.8.9/StakingRouter.sol#L146

2024-09-06 08:24 UTC, vp4242 commented on contracts/testnets/sepolia/SepoliaDepositAdapter.sol
> +        ISepoliaDepositContract(0x7f02C3E3c98b133055B8B348B2Ac625669Ed295D);
technically it's totally fine to use ctror but it's questionable if that ever make sense to change orginal deposit contract in the first place. It's very unlikely that it will change for sepolia. although I don't mind putting back the old logic

2024-09-06 13:03 UTC, TheDZhon commented on contracts/testnets/sepolia/SepoliaDepositAdapter.sol
> +        ISepoliaDepositContract(0x7f02C3E3c98b133055B8B348B2Ac625669Ed295D);
no strong feelings since it resides within `testnets/sepolia`, yeah

2024-09-06 13:06 UTC, TheDZhon approved these changes
Resplendent :gem:

2024-09-06 14:10 UTC, tamtamchik requested changes
Please incorporate a setup for running tests in the pull request. I also have some minor suggestions for code cleanup and test structuring.

2024-09-06 14:10 UTC, tamtamchik commented on test/testnets/sepolia/sepolia-deposit-adapter.test.ts
> +    it("recover Bepolia tokens", async () => {
I suggest using a common unit tests file structure. Use the `context` of the function name in `it` blocks with the desired outcome. This one, for example, should have this structure:
- context("recoverBepolia")
  - it("Reverts with when calling owner was not successful")
  - it("Emits BepoliaRecovered on successful bepolia token recovery")
  
And so on. This approach makes it easy to identify uncovered cases for tests.

2024-09-06 16:29 UTC, vp4242 commented on test/testnets/sepolia/sepolia-deposit-adapter.test.ts
> +  const bepoliaTokenHolder = EOAddress;
It's our EOA address for Sepolia. There is no really a page for that. That could be done is to use bepolia contract of the tokens itself.

2024-09-06 16:53 UTC, vp4242 commented on test/testnets/sepolia/sepolia-deposit-adapter.test.ts
> +  };
Let's fix that separately. There is no straightforward log.debug() that accepts strings, only structures. I'm concerned that this PR is blocked

2024-09-06 16:54 UTC, vp4242 commented on test/testnets/sepolia/sepolia-deposit-adapter.test.ts
> +    if (chainId !== 11155111n) {
I've added a comment about test running and will think if that's feasible to have it in docs/package.json

2024-09-06 16:55 UTC, vp4242 commented on test/testnets/sepolia/sepolia-deposit-adapter.test.ts
> +      const dataRoot = "0x8b09ed1d0fb3b8e3bb8398c6b77ee3d8e4f67c23cb70555167310ef02b06e5f5";
it's just random values suitable to call. Do you suggest to write helpers to randomize it? I think it's overkill

2024-09-06 17:04 UTC, tamtamchik commented on test/testnets/sepolia/sepolia-deposit-adapter.test.ts
> +      const dataRoot = "0x8b09ed1d0fb3b8e3bb8398c6b77ee3d8e4f67c23cb70555167310ef02b06e5f5";
No, I suggest leaving a comment somewhere that it is just a bunch of random values. I thought this is some real data :)

2024-09-06 17:04 UTC, vp4242 commented on test/testnets/sepolia/sepolia-deposit-adapter.test.ts
> +    it("recover Bepolia tokens", async () => {
I would question convenience of this structure. For complex functions maybe it's better approach but the functions are small here. Maybe it's better to just leave those 5 test cases without a context?

2024-09-06 17:04 UTC, tamtamchik commented on test/testnets/sepolia/sepolia-deposit-adapter.test.ts
> +  };
This is not a stopper, just a suggestion. Not blocking merge.

2024-09-06 17:06 UTC, tamtamchik commented on test/testnets/sepolia/sepolia-deposit-adapter.test.ts
> +    it("recover Bepolia tokens", async () => {
Also, it's not a blocker, but a suggestion.

2024-09-06 17:07 UTC, tamtamchik commented on test/testnets/sepolia/sepolia-deposit-adapter.test.ts
> +    if (chainId !== 11155111n) {
Works for me.

2024-09-06 17:08 UTC, tamtamchik approved these changes
Now it is possible to re-run the test. Approved the PR! 
Thank you for your effort on this Friday evening! 🍻

2024-09-06 17:21 UTC, vp4242 commented
Thank you for the detailed review! I'll address other suggestions in a separate PR

2024-09-06 17:21 UTC, merged