Negative rebase limit
lidofinance/core pull request #67
Opened 2024-04-05 07:58 UTC by vp42ldo

Negative rebase limit

2024-04-08 21:21 UTC, TheDZhon requested changes
:+1: It's an excellent way to push things closer to Mainnet.

I suggest considering my comments and findings to improve the code and figure out the plan forward with audits :goggles:

2024-04-08 21:21 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +interface ILidoZKOracle {
```suggestion
interface ILidoCLStateOracle {
```

2024-04-08 21:21 UTC, TheDZhon commented on test/0.8.9/contracts/OracleReportSanityCheckerWrapper.sol
> +// SPDX-License-Identifier: GPL-3.0
```suggestion
// SPDX-FileCopyrightText: 2024 Lido <info@lido.fi>
// SPDX-License-Identifier: GPL-3.0
// NB: for testing purposes only
```

2024-04-08 21:21 UTC, TheDZhon commented on test/0.8.9/contracts/ZkOracleMock.sol
> +// SPDX-License-Identifier: GPL-3.0
```suggestion
// SPDX-FileCopyrightText: 2024 Lido <info@lido.fi>
// SPDX-License-Identifier: GPL-3.0
// NB: for testing purposes only
```

2024-04-08 21:21 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        _checkOneOffCLBalanceDecrease(limitsList, _preCLBalance,
I would rather rename this method tbh

2024-04-08 21:21 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    /// @param negativeRebaseOracle address of the negative rebase oracle
may add a remark that the address might be zero

2024-04-08 21:21 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    function getNegativeRebaseOracle() public view returns (address) {
```suggestion
    function getCLStateOracle() public view returns (address) {
```

2024-04-08 21:21 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    function setNegativeRebaseOracle(address negativeRebaseOracle) external onlyRole(DEFAULT_ADMIN_ROLE) {
```suggestion
    function setCLStateOracle(address clStateOracle) external onlyRole(DEFAULT_ADMIN_ROLE) {
```

2024-04-08 21:21 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +struct RebaseData {
```suggestion
struct CLRebaseData {
```

2024-04-08 21:21 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    uint64 rebaseValue;
```suggestion
    uint192 clRebaseValue;
```

as Solidity/EVM use 32-bytes long machine words, it doesn't make sense to make struct fields narrower than that

2024-04-09 07:33 UTC, vp42ldo commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
>          if (oneOffCLBalanceDecreaseBP > _limitsList.oneOffCLBalanceDecreaseBPLimit) {
that's a good question. Probably not as the new one will prevail. I will remove it then

2024-04-09 07:40 UTC, vp42ldo commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    uint64 rebaseValue;
unless we would like to pack it. I guess we won't in this case

2024-04-15 11:06 UTC, folkyatina commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    function setCLBalanceOraclesDiffBPLimit(uint256 _cLBalanceOraclesDiffBPLimit)
Error Margin?

2024-04-15 11:09 UTC, folkyatina commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    function sumRebaseValuesNotOlderThan(uint256 _timestamp) public view returns (uint256) {
Is this intentionally left public? If so, it requires to be placed upper in the file and some NatSpec should be added

2024-04-15 11:40 UTC, folkyatina approved these changes
Thanks for your work. Minor suggestions for the contract.

2024-04-15 11:40 UTC, folkyatina commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        // NOTE: Base points is 10_000, so 320 BP is 3.20%
Comment is irrelevant

2024-04-15 11:40 UTC, folkyatina commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        uint256 balanceDiffBP = MAX_BASIS_POINTS * rebaseSum / (_unifiedPostCLBalance + rebaseSum);
Loss of precision because of int division can influence the comparison later. Maybe redo the calculations to get rid of the division?

2024-04-15 11:40 UTC, folkyatina commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +            revert IncorrectCLBalanceDecreaseForSpan(balanceDiffBP);
The error name looks like it should be a span parameter also.

2024-04-15 11:40 UTC, folkyatina commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +            // NOTE: Base points is 10_000, so 74 BP is 0.74%
irrelevant comment

2024-04-15 11:40 UTC, folkyatina commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +            if (balanceDifferenceBP >= _limitsList.cLBalanceOraclesDiffBPLimit) {
This comparison does not suffer from precision loss, but maybe it's worth making it uniformly.

2024-04-15 11:40 UTC, folkyatina commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +            ILidoBaseOracle(accountingOracle).GENESIS_TIME()) /
It looks like GENESIS_TIME and SECONDS_PER_SLOT can be immutable contract members initialized in the constructor because they do not change after deployment, only from chain to chain.

2024-04-15 12:43 UTC, vp4242 commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    function setCLBalanceOraclesDiffBPLimit(uint256 _cLBalanceOraclesDiffBPLimit)
?

2024-04-15 12:47 UTC, vp4242 commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    function sumRebaseValuesNotOlderThan(uint256 _timestamp) public view returns (uint256) {
thanks. I don't mind making it internal but it seems that public is more transparent

2024-04-15 12:55 UTC, folkyatina commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    function setCLBalanceOraclesDiffBPLimit(uint256 _cLBalanceOraclesDiffBPLimit)
Just a suggestion for better naming

2024-04-17 11:43 UTC, TheDZhon requested changes
Thank you for polishing up this project further :star_struck: 

I'd recommend to revise some of the approaches used, see the review comments :pray:

2024-04-17 11:43 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +interface ILidoBaseOracle {
```suggestion
interface IBaseOracle {
```

2024-04-17 11:43 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +	);
please check the formatting

2024-04-17 11:43 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    ///     as reported by the Oracle and the state of the Consensus Layer Oracle.
```suggestion
    ///     as reported by the AccountingOracle and the state of the Consensus Layer Oracle.
```

2024-04-17 11:43 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
>  struct LimitsListPacked {
let's try to find some space to make this struct occupying only a single storage slot :warning: 

now it's 272 bits while we can shorten some fields to make it ≤256, e.g. make `requestTimestampMargin` as `uint48`

2024-04-17 11:43 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    CLRebaseData[] private _rebaseData;
```suggestion
    CLRebaseData[] private _clRebases;
```

2024-04-17 11:43 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    function setCLBalanceDecreaseHoursSpan(uint256 _cLBalanceDecreaseHoursSpan)
I am not entirely convinced if we need to change both values separately and not via a single method, wdyt?

e.g.:

```solidity
function setCLBalanceDecreaseLimit(uint256 _clBalanceDrecreaseBPLimit, uint256 _clBalanceDecreaseHoursSpan)
```

2024-04-17 11:43 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    function setCLBalanceOraclesErrorMarginBPLimit(uint256 _cLBalanceOraclesErrorMarginBPLimit)
it might be needed to set together with the cl oracle :thinking:

2024-04-17 11:43 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        while (slot >= 0) {
Why not old plain ~soviet~ for loop?

2024-04-17 11:43 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        uint256 rebaseValuesSum = 0;
```suggestion
        uint256 rebaseValuesSum;
```

gas golfing, haha (disregard if you find yourself uncomfortable with this change)

2024-04-17 11:43 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        _rebaseData.push(CLRebaseData(SafeCast192.toUint192(_value), SafeCast.toUint64(_timestamp)));
shall we enforce invariants for this data?

2024-04-17 11:43 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +library SafeCast192 {
Let's extract this to a separate file or not introduce a library at all

2024-04-17 11:43 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        int256 slot = int256(_rebaseData.length) - 1;
```suggestion
        int256 clRebaseIndex = int256(_rebaseData.length) - 1;
```

:warning: let's avoid using the `slot` term here because it's a bit ambiguous (it might be confused with the Consensus Layer slots)

2024-04-17 11:43 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        while (slot >= 0) {
e.g.:

```solidity
for(int256 clRebaseIndex = int256(_rebaseData.length) - 1; clRebaseIndex >= 0; --clRebaseIndex)
```

2024-04-17 11:43 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
>          if (_preCLBalance <= _unifiedPostCLBalance) return;
I would document this early return tbh

2024-04-17 11:43 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        _addRebaseValue(_preCLBalance - _unifiedPostCLBalance, _reportTimestamp);
```suggestion
        _addNegativeCLRebase(_preCLBalance - _unifiedPostCLBalance, _reportTimestamp);
```

2024-04-17 11:43 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        uint256 rebaseSum = sumRebaseValuesNotOlderThan(pastTimestamp);
It reads like we sum up every rebase, while looking only for negative ones :warning:

2024-04-17 11:43 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        // If there is no negative rebase oracle, then we don't need to check the zk report
Why 'zk' report? usage of zk technology for this oracle shouldn't be taken for granted

2024-04-17 11:43 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +            revert CLStateReportIsNotReady();
Should this error have a bit different name to say something like '**can't verify negative rebase** because of the missing cl oracle report'?

2024-04-17 11:43 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +            emit ConfirmNegativeRebase(refSlot, clBalanceWei);
```suggestion
            emit NegativeRebaseConfirmed(refSlot, clBalanceWei);
```

events usually use past tense

2024-04-17 12:31 UTC, vp4242 commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    function setCLBalanceDecreaseHoursSpan(uint256 _cLBalanceDecreaseHoursSpan)
Pros: less functions
Cons: may accidentally change other value

🤷‍♂️

2024-04-17 12:35 UTC, vp4242 commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    function setCLBalanceOraclesErrorMarginBPLimit(uint256 _cLBalanceOraclesErrorMarginBPLimit)
that probably make sense since there should be direct deps on each other

2024-04-17 12:35 UTC, vp4242 commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    function setCLBalanceDecreaseHoursSpan(uint256 _cLBalanceDecreaseHoursSpan)
those values are used together within the check, so it's probably worth checking that they aligned

2024-04-17 12:47 UTC, vp4242 commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +            revert CLStateReportIsNotReady();
In that case it's probably worth changing other error to confirm this naming logic

2024-04-17 15:53 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        _rebaseData.push(CLRebaseData(SafeCast192.toUint192(_value), SafeCast.toUint64(_timestamp)));
yep

2024-04-17 15:58 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    function setCLBalanceDecreaseHoursSpan(uint256 _cLBalanceDecreaseHoursSpan)
> Cons: may accidentally change other value
For me t's vise versa: way more easier to change one value and accidentally forget about their coupling

2024-04-24 09:20 UTC, avsetsin commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        uint256 _reportTimestamp
⚠️ This method is expected `_reportTimestamp` as an argument, but it's called from `checkAccountingOracleReport` with `_timeElapsed`: https://github.com/lidofinance/core/blob/e2c8ba8c785d552751b47d5240c7cbe8ea4802bd/contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol#L500-L502

2024-04-24 14:41 UTC, avsetsin commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        address clStateOracle = getCLStateOracle();
I would suggest to consider a more flexible implementation. Right now it seems that the interface of the second opinion is mainly dictated by the implementation of the ZKP oracle.

A more flexible option might be a push model rather than a pool model. SanityChecker, in case some event occurs (in our case rebase below treshold), could ask for some second opinion contract by sending the values of the current report. Smth like:

```solidity
interface SecondOpinion {
    wdyt(
        uint256 _timeElapsed,
        uint256 _preCLBalance,
        uint256 _postCLBalance,
        uint256 _withdrawalVaultBalance,
        uint256 _preCLValidators,
        uint256 _postCLValidators
    ) external;
}
```

The second opinion contract in this case could be quite variable:
- check against the ZKP oracle report
- check against beacon root proof of state.slashings or inactivity leak
- check against approved values by a multisig

2024-04-24 14:41 UTC, avsetsin commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +            if (balanceDifferenceBP >= _limitsList.cLBalanceOraclesErrorMarginBPLimit) {
Abstraction leaked. Sanity check contract knows that ZKP oracle has some peculiarities. I guess it's better to handle this on ZKP oracle contract side

2024-04-24 14:41 UTC, avsetsin commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +            uint256 balanceDifferenceBP = MAX_BASIS_POINTS * balanceDiff / clBalanceWei;
⚠️ Division by 0 can happen here when there are no validators left on CL

2024-04-24 15:05 UTC, vp4242 commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +            if (balanceDifferenceBP >= _limitsList.cLBalanceOraclesErrorMarginBPLimit) {
in the current design it's not possible but I see your point

2024-04-24 15:07 UTC, vp4242 commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +            if (balanceDifferenceBP >= _limitsList.cLBalanceOraclesErrorMarginBPLimit) {
in other case it was critical about precision. here it'is not but considering div by 0 case — worth changing as well

2024-04-27 10:01 UTC, avsetsin commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +                sum += _clNegativeRebases[uint256(index)].value;
I think there is an issue if you operate with absolute values: https://hackmd.io/@lido/HkRweE9Z0

2024-05-07 10:07 UTC, TheDZhon requested changes
LGTM except only for a few improvements and edits

2024-05-07 10:07 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        uint256 reportTimestamp
should it be rolled back?

2024-05-19 08:33 UTC, TheDZhon approved these changes
Godspeed :rocket: 

Left some _minorish_ things only

2024-05-19 08:33 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    uint64 exitedValidatorsCount;
nitpick: just to be compat with the `StakingModuleSummary` struct naming.

```suggestion
    uint64 totalExitedValidators;
```

2024-05-19 08:33 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    uint128 negativeCLRebase;
nitpick: just to avoid future confusion

```suggestion
    uint128 negativeCLRebaseWei;
```

2024-05-19 08:33 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        }
nitpick:

```suggestion
        if (_preCLBalance <= _unifiedPostCLBalance) {
             _addReportData(reportTimestamp, stakingRouterExitedValidators, 0);
            // If the CL balance is not decreased, we don't need to check anyting here
            return;
        }
        _addReportData(reportTimestamp, stakingRouterExitedValidators, _preCLBalance - _unifiedPostCLBalance);
```

2024-05-19 08:33 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        uint256 maxCLRebaseNegativeSum =
```suggestion
        uint256 maxAllowedCLRebaseNegativeSum =
```

2024-05-19 08:33 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +            revert NegativeRebaseFailedCLStateReportIsNotReady();
```suggestion
            revert NegativeRebaseFailedSecondOpinionReportIsNotReady();
```

2024-05-19 08:33 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +            emit PenaltiesAmountSet(_newLimitsList.inactivityPenaltiesAmountPWei);
```suggestion
            emit InactivityPenaltiesAmountSet(_newLimitsList.inactivityPenaltiesAmountPWei);
```

2024-06-13 08:56 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        (bool success, uint256 clOracleBalanceGwei,,) = secondOpinionOracle.getReport(_refSlot);
should it have the withdrawal vault balance included?

2024-06-13 09:00 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        if (msg.sender != LIDO_LOCATOR.lido()) {
let's save LIDO in immutable var

2024-06-17 16:18 UTC, TheDZhon requested changes
:eyes:

2024-06-17 16:18 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +            uint256 withdrawalVaultBalance,
```suggestion
            uint256 withdrawalVaultBalanceWei,
```

2024-06-17 16:18 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> -        uint256 unifiedPostCLBalance = _postCLBalance + _withdrawalVaultBalance;
I am not sure if we need to remove this var and recalculate it here and there

2024-06-17 16:18 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        (bool success, uint256 clOracleBalanceGwei, uint256 oracleWithdrawalVaultBalance,,) = secondOpinionOracle.getReport(_refSlot);
let's name it `oracleWithdrawalVaultBalanceWei`

2024-06-17 16:20 UTC, vp4242 commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> -        uint256 unifiedPostCLBalance = _postCLBalance + _withdrawalVaultBalance;
it's Solidity limitation on number of local vars

2024-06-18 14:47 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> -        uint256 unifiedPostCLBalance = _postCLBalance + _withdrawalVaultBalance;
I see

2024-06-18 14:49 UTC, TheDZhon commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        _addReportData(reportTimestamp, stakingRouterExitedValidators, _preCLBalance - _postCLBalance - _withdrawalVaultBalance);
```suggestion
        _addReportData(reportTimestamp, stakingRouterExitedValidators, _preCLBalance - (_postCLBalance + _withdrawalVaultBalance));
```

2024-07-08 15:18 UTC, avsetsin commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +            IStakingRouter.StakingModuleSummary memory summary = stakingRouter.getStakingModuleSummary(ids[i]);
It would be great to have integration tests for checks related to exited validators since there's a pretty complex logic behind the delivery of that data.

2024-07-08 18:55 UTC, avsetsin commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        if (_oldLimitsList.initialSlashingAmountPWei != _newLimitsList.initialSlashingAmountPWei) {
Nitpicking, feel free to ignore it. Consider spelling `Gwei` and `PWei` the same way (`PWei` -> `Pwei`)

2024-07-08 18:55 UTC, avsetsin commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    }
Since it mutates store consider emitting an event here

2024-07-08 18:55 UTC, avsetsin commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +            if (reportData[uint256(index)].timestamp > SafeCast.toUint64(_timestamp)) {
A small suggestion: the code can be simplified on int <> uint conversion if we put an element in `reportData` in the constructor beforehand. 

It safe to put there something like `(GENESIS_TIME, 0, 0)`

2024-07-09 07:40 UTC, avsetsin commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        LimitsList memory _limitsList
Changes in the constructor (new values in the `_limitsList` struct and getting rid of `_managersRoster`) should affect the scratch deployment, which is probably broken now

2024-07-09 07:55 UTC, avsetsin commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> -    uint256 oneOffCLBalanceDecreaseBPLimit;
Removing an element from the middle of the struct breaks a backward compatibility in the `getOracleReportLimits` method.

2024-07-09 09:50 UTC, vp4242 commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        LimitsList memory _limitsList
That's for sure but it's intended to remove unused complexity in roles management

2024-07-09 13:30 UTC, avsetsin commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        LimitsList memory _limitsList
I mean, pls check scratch deployment scripts

2024-07-11 11:04 UTC, vp4242 commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        uint256 refSlot = IBaseOracle(LIDO_LOCATOR.accountingOracle()).getLastProcessingRefSlot();
That's true. I would prefer the dependency could be avoided but that requires Lido contract change and formal re-audit for it.

2024-07-11 11:15 UTC, vp4242 commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        LimitsList memory _limitsList
Indeed deployment scripts requires changes. Will be fixed in a separate PR

2024-07-11 11:49 UTC, vp4242 commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> -    uint256 oneOffCLBalanceDecreaseBPLimit;
Added comment about this to the spec https://github.com/lidofinance/lido-improvement-proposals/pull/61

2024-07-11 14:19 UTC, vp4242 commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        LimitsList memory _limitsList
Actually applying deployment script fixes now

2024-07-17 16:10 UTC, vp4242 commented on test/0.4.24/contracts/AccountingOracle__MockForLegacyOracle.sol
It's no longer necessary as tests for negative rebase are using AccountingOracle__MockForSanityChecker

2024-07-17 16:14 UTC, vp4242 commented on test/0.8.9/contracts/OracleReportSanityCheckerWrapper.sol
> +contract OracleReportSanityCheckerWrapper is OracleReportSanityChecker {
"Harness" in naming it's a pretty recent naming practice. I would do it separately

2024-07-17 16:27 UTC, vp4242 commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    uint256 inactivityPenaltiesAmountPWei;
I would argue that max is a bit redundant here. The same logic could be applied for naming of initialSlashingAmountPWei. Seems that the change doesn't bring a lot of clarity to already long name

2024-07-17 16:39 UTC, vp4242 commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +            _limitsList.initialSlashingAmountPWei * ONE_PWEI * (_postCLValidators - _exitedValidatorsAtTimestamp(reportTimestamp - 18 days)) +
It's 2200 of gas reduction in case of a single loop AFAIK. Do you think it's worth it for the current state?

2024-07-18 20:25 UTC, TheDZhon approved these changes
LGTM

2024-07-19 07:19 UTC, TheDZhon requested changes
:eyes:

2024-07-19 07:19 UTC, TheDZhon commented on contracts/0.8.9/interfaces/ISecondOpinionOracle.sol
> +pragma solidity >=0.4.24 <0.9.0;
:warning: On condition of using the wide pragma condition, it makes much more sense putting this interface to the `contracts/common/interfaces`

2024-07-19 07:25 UTC, TheDZhon approved these changes
:ship:

2024-07-19 09:22 UTC, merged