Lido v2 fix comments
lidofinance/core pull request #779
Opened 2023-06-27 08:20 UTC by folkyatina

Aggregate contract comment fixes related to v2 here

2023-06-27 16:33 UTC, TheDZhon reviewed
:+1: Like it

Left some suggestions.

Worth discussing the general approach regarding re-deployments here.

2023-06-27 16:33 UTC, TheDZhon commented on README.md
> +The Lido Ethereum Liquid Staking Protocol allows their users to earn staking rewards on the Beacon chain without locking ether or maintaining staking infrastru ether
kind a glitch here: `infrastru ether`

2023-06-27 16:33 UTC, TheDZhon commented on contracts/0.4.24/StETH.sol
> + * which change `shares`. `_stop` and `_resume` functions are overridden
nice catch!

2023-06-27 16:33 UTC, TheDZhon commented on contracts/0.4.24/StETH.sol
> +     * - `_recipient` cannot be the zero address or stETH contract itself.
`or _the_ stETH contract`

2023-06-27 16:33 UTC, TheDZhon commented on contracts/0.4.24/StETH.sol
> +     * - `_recipient` cannot be the zero address or stETH contract itself.
`the stETH contract`

2023-06-27 16:33 UTC, TheDZhon commented on contracts/0.4.24/StETH.sol
> +     * Emits an `Approval` event indicating the updated allowance.
I think it's not emitted if the allowance is unlimited, is it?

2023-08-15 13:37 UTC, TheDZhon requested changes
Overall is good though a bit of chores would be nice to have :pray:

2023-08-15 13:37 UTC, TheDZhon commented on contracts/0.4.24/Lido.sol
> +    * @notice Send funds to the pool and mints `StETH` tokens to `msg.sender` address
Maybe 'send' doesn't collocate with 'mints' here :thinking: 
also, tokens to **the** `msg.sender` address

2023-08-15 13:37 UTC, TheDZhon commented on contracts/0.4.24/Lido.sol
> +     * @notice Send funds to the pool with the optional `_referral` parameter and mints `StETH` tokens to `msg.sender` address
The same as above

2023-09-12 23:07 UTC, Itzyboo1 reviewed
I think
It looks better

2024-09-04 07:39 UTC, mymphe commented
Leaving this PR open as a reminder for the next upgrade but the repo is no longer maintained. LidoFinance protocol moved to [core repository](https://github.com/lidofinance/core).

2024-12-18 11:48 UTC, mymphe commented on contracts/0.4.24/StETH.sol
> - * of Ether controlled by the protocol. Account shares aren't normalized, so the
sdfasdf

2025-02-17 04:57 UTC, dav3yblaz3 approved these changes
let us get these changes done for test thanks team

2025-04-11 13:52 UTC, tamtamchik commented
Will close since will be partially implemented with #874

2025-04-11 13:52 UTC, closed without merging