Accounting oracle tests
lidofinance/core pull request #83
Opened 2024-04-23 12:00 UTC by vp4242

Accounting oracle tests

2024-05-03 10:34 UTC, mymphe requested changes

2024-05-03 10:34 UTC, mymphe commented on test/0.8.9/oracle/accountingOracleAccessControl.test.ts
> +    beforeEach(deploy);
Why don't we just `beforeEach` once in the outer context? If we need to use different `extraData`, we can just submit a new report inside the inner context with the necessary `extraData`?

2024-05-03 14:01 UTC, vp4242 commented on lib/locator-deploy.ts
> +async function getLocatorConfig(locatorAddress: string) {
It seems, I can't. dummyLocator is using LidoLocator Mutable Mock but here it's LidoLocator expected.

2024-05-03 14:12 UTC, vp4242 commented on lib/string.ts
> +export function hex(n: number, byteLen: number | undefined = undefined) {
bigintToHex() works with bigints that requires conversion from number to bigint. Looks like an overhead

2024-05-03 14:23 UTC, vp4242 commented on test/0.8.9/oracle/accountingOracleSubmitReportExtraData.test.ts
> +  }
why?

2024-05-03 14:24 UTC, vp4242 commented on test/0.8.9/oracle/accountingOracleAccessControl.test.ts
> +        await expect(tx).to.emit(oracle, "ExtraDataSubmitted").withArgs(reportFields.refSlot, anyValue, anyValue);
yes but isn't that more readable this way?

2024-05-03 14:31 UTC, vp4242 commented on test/0.8.9/oracle/accountingOracleDeploy.test.ts
> +    it(`init fails if the initial epoch of the new oracle is not the next frame's first epoch`, async () => {
I'm not the author of the original tests but they make sense to me. Could you elaborate on this particular case?

2024-05-03 14:37 UTC, vp4242 commented on lib/string.ts
> +export function hex(n: number, byteLen: number | undefined = undefined) {
I did the implementation for numberToHex() with bigintToHex() but can't say I like it this way. wdyt?

2024-05-20 08:15 UTC, mymphe approved these changes

2024-05-20 08:15 UTC, mymphe commented on lib/dummy.ts
> +  return await ethers.getContractAt("LidoLocator", await proxy.getAddress());
Also, I don't think using contact names to refer to the build artifact is a good pattern. What do you think about using `attach`? It returns a new instance of the contract with the same ABI but at a different address.

```suggestion
  return locator.attach(proxy.getAddress());
```

More
https://docs.ethers.org/v6/api/contract/#BaseContract-attach

2024-05-20 08:15 UTC, mymphe commented on lib/dummy.ts
> +  const proxy = await ethers.getContractAt("OssifiableProxy", proxyAddress);
Here as well. It's better to use `typechain` factories rather than strings to refer to artifacts.

2024-05-20 08:15 UTC, mymphe commented on lib/dummy.ts
> +  };
A small optimization that I would suggest is to parallelize these requests using `Promise.all`.

2024-05-20 09:50 UTC, mymphe commented on lib/dummy.ts
> +    await locator.oracleDaemonConfig(),
Don't need to `await`. `Promise.all` accepts promises

2024-05-20 10:44 UTC, merged