[Vault] Dashboard recovery
lidofinance/core pull request #908
Opened 2024-12-26 07:06 UTC by Jeday

## Context

- adds minimal `recover` method to dashboard that allows admin to recover all ether/erc20 
- tests for it

## Question
Should we throw events?

2025-01-09 13:14 UTC, tamtamchik requested changes
Need to at least have events for recovery

2025-01-09 13:14 UTC, tamtamchik commented on contracts/0.8.25/vaults/Dashboard.sol
> +            payable(msg.sender).transfer(address(this).balance);
Emit event?

2025-01-09 13:14 UTC, tamtamchik commented on contracts/0.8.25/vaults/Dashboard.sol
> +            if (!success) revert("ERC20: Transfer failed");
Emit event?

2025-01-09 13:14 UTC, tamtamchik commented on contracts/0.8.25/vaults/Dashboard.sol
> +     * @notice recovers ERC20 tokens or ether from the vault
What if we need to recover shares / ERC721 (withdrawals NFT) / ERC1155 anything. Maybe there is a library we can use?

2025-01-10 09:35 UTC, Jeday commented on contracts/0.8.25/vaults/Dashboard.sol
> +     * @notice recovers ERC20 tokens or ether from the vault
https://github.com/OpenZeppelin/openzeppelin-contracts/pull/1474#issuecomment-441051976
No trusted libs, but will implement nft recovery.

2025-01-10 11:08 UTC, Jeday commented on contracts/0.8.25/vaults/Dashboard.sol
> +            payable(msg.sender).transfer(address(this).balance);
fixed

2025-01-10 11:08 UTC, Jeday commented on contracts/0.8.25/vaults/Dashboard.sol
> +            if (!success) revert("ERC20: Transfer failed");
fixed

2025-01-14 09:13 UTC, Jeday commented on contracts/0.8.25/vaults/Dashboard.sol
> +     * @notice recovers ERC20 tokens or ether from the vault
fixed

2025-01-14 11:41 UTC, tamtamchik approved these changes
Some minor tweaks, but all-in-all approved

2025-01-14 11:41 UTC, tamtamchik commented on contracts/0.8.25/vaults/Dashboard.sol
> +    address public constant ETH = address(0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE);
```suggestion
    address public constant ETH = address(0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee);
```

`0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE` is actually not ERC-1191 compliant, the correct address should be `0xeeeEEEeEEeeeEeEeEEEeEeeeeEEEEeEEeEeeeeeE`

ERC-1191 does checksum encoding using chainId, see the spec here: [https://github.com/ethereum/ercs/blob/master/ERCS/erc-1191.md 12](https://github.com/ethereum/ercs/blob/master/ERCS/erc-1191.md)

Source: https://ethereum-magicians.org/t/eip-7528-eth-native-asset-address-convention/15989/13

Would suggest sticking to all lowercase, just for sanity reasons.

2025-01-14 11:41 UTC, tamtamchik commented on contracts/0.8.25/vaults/Dashboard.sol
> +     * @param _token Address of the token to recover, 0 for ether
```suggestion
     * @param _token Address of the token to recover, 0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee for ether
```

2025-01-14 11:48 UTC, Jeday commented on contracts/0.8.25/vaults/Dashboard.sol
> +     * @param _token Address of the token to recover, 0 for ether
fixed

2025-01-14 11:48 UTC, Jeday commented on contracts/0.8.25/vaults/Dashboard.sol
> +    address public constant ETH = address(0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE);
fixed to lowercase

2025-01-14 11:50 UTC, Jeday commented on contracts/0.8.25/vaults/Dashboard.sol
> +    address public constant ETH = address(0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE);
actually linter breaks on this

2025-01-14 11:51 UTC, merged