Fix accounting tests for vaults
lidofinance/core pull request #912
Opened 2024-12-30 16:55 UTC by vp4242

Fix accounting tests for vaults

2025-01-03 11:36 UTC, folkyatina commented on test/0.4.24/lido/lido.accounting.test.ts
> +      await updateLidoLocatorImplementation(await lido.getLidoLocator(), { accounting: deployer });
Looks like it's cleaner to impersonate accountOracle contract address in before and connect it as a default one.

2025-01-14 13:37 UTC, folkyatina commented on test/0.4.24/lido/lido.accounting.test.ts
> +    type ArgsTuple = [bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint];
I believe that there should be better solution for this typing. E.g. reuse some types generated by typechain. Maybe, it's worth to get rid of it.

2025-01-14 14:02 UTC, folkyatina requested changes
I suggest to reframe it as a unit tests, without testing the lido+accounting duo together

2025-01-14 14:02 UTC, folkyatina commented on test/deploy/dao.ts
> +  const locator = await lido.getLidoLocator();
Looks like these lines add accounting deployment to the dozen of different test suites. Do we really need it this way? It will slow down all the test pipeline. Maybe, we need a separate function for it?

2025-01-14 14:02 UTC, folkyatina commented on test/0.8.9/contracts/oracle/OracleReportSanityCheckerMocks.sol
> -    function checkSimulatedShareRate(
Seems like this contract is not used at all and may be deleted safely. Probably, even the whole file.

2025-01-14 14:02 UTC, folkyatina commented on test/0.8.9/accounting.handleOracleReport.test.ts
> +  context("handleOracleReport", () => {
it seems like this tests becomes partially integration one (because it's testing accounting+lido), not a unit test. And so we're having some ugly hacks with direct storage checks here. 

I'd suggest to introduce a Lido mock here and test using it and test accounting methods in lido separately.

2025-01-14 18:00 UTC, vp4242 commented on test/0.4.24/lido/lido.accounting.test.ts
> +    type ArgsTuple = [bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint];
Unlike `accounting.handleOracleReport()` the Lido's `processClStateUpdate()` accepts parameters of basic types (uint256) and not a structure. typechain type in that case just a `ContractMethodArgs< A extends Array<any>,   S extends StateMutability>` which makes the parameters to `handleOracleReport()` just an array of bigints. I'll look once again at this but so far I can't propose better approach here

2025-01-16 14:20 UTC, folkyatina reviewed
Almost ready to merge

2025-01-16 14:20 UTC, folkyatina commented on test/0.4.24/lido/lido.accounting.test.ts
> +  let oracleReportSanityChecker: OracleReportSanityChecker__MockForAccounting;
Lido don't use sanity checker anymore, so we can skip this part of initialization.

2025-01-16 14:20 UTC, folkyatina commented on test/0.4.24/lido/lido.accounting.test.ts
> +  let postTokenRebaseReceiver: IPostTokenRebaseReceiver;
Lido don't use postTokenRebaseReceiver too, so we can skip it.

2025-01-16 14:20 UTC, folkyatina commented on test/0.8.9/accounting.handleOracleReport.test.ts
> +  let elRewardsVault: LidoExecutionLayerRewardsVault__MockForLidoAccounting;
We can remove excess dependencies if testing only Accounting: elRewardsVault and withdrawalVault

2025-01-16 14:20 UTC, folkyatina commented on test/0.8.9/accounting.handleOracleReport.test.ts
> +      // second report, 101 validators
Looks like the test misses actual reporting and checks

2025-01-16 14:20 UTC, folkyatina commented on test/0.8.9/accounting.handleOracleReport.test.ts
> +      await expect(accounting.handleOracleReport(report())).to.be.reverted;
Need to check the exact reason

2025-01-16 14:20 UTC, folkyatina commented on test/0.8.9/accounting.handleOracleReport.test.ts
> +      ).to.be.reverted;
Need to check the reason

2025-01-16 14:20 UTC, folkyatina commented on test/0.8.9/accounting.handleOracleReport.test.ts
> +    // it("Does not revert if the `checkWithdrawalQueueOracleReport` sanity check fails but `withdrawalQueue` is paused", async () => {
It maybe a bug in a new Accounting, BTW. Need to check.

2025-01-16 14:20 UTC, folkyatina commented on test/0.8.9/accounting.handleOracleReport.test.ts
> +    it("Does not emit `StETHBurnRequested` if there are no shares to burn", async () => {
Strange to check the actual event from Burner contract in Accounting unit tests. Probably, the mock event will be better.

2025-01-16 14:20 UTC, folkyatina commented on test/0.8.9/accounting.handleOracleReport.test.ts
> +    it("Emits `StETHBurnRequested` if there are shares to burn", async () => {
Same here.

2025-01-16 14:20 UTC, folkyatina commented on test/0.8.9/accounting.handleOracleReport.test.ts
> +        .to.emit(burner, "Mock__CommitSharesToBurnWasCalled")
👍

2025-01-16 14:58 UTC, vp4242 commented on test/0.8.9/accounting.handleOracleReport.test.ts
> +    it("Does not emit `StETHBurnRequested` if there are no shares to burn", async () => {
It's actually event from mocked contract. Will rename it to `Mock__StETHBurnRequested`

2025-01-16 15:05 UTC, vp4242 commented on test/0.8.9/accounting.handleOracleReport.test.ts
> +    // it("Does not revert if the `checkWithdrawalQueueOracleReport` sanity check fails but `withdrawalQueue` is paused", async () => {
Could be. Previous implementation have explicit check for pause state
https://github.com/lidofinance/core/blob/901c0e19b752f5ea03118d71881d8b72ccee44c0/contracts/0.4.24/Lido.sol#L879

2025-01-19 11:20 UTC, folkyatina approved these changes
:shipit:

2025-01-19 11:20 UTC, folkyatina commented on test/0.8.9/accounting.handleOracleReport.test.ts
> +        .and.to.emit(lido, "TransferShares")
Looks like formatter troubles

2025-01-21 16:29 UTC, merged