multi-transaction oracle third phase
lidofinance/core pull request #97
Opened 2024-05-23 14:35 UTC by mkurayan

Depending on the size of the third-phase report, it may be split into multiple transactions.

2024-05-30 19:12 UTC, krogla requested changes
sanity checker refactor required

suggest PR #99 with lastSortingKey fix

2024-05-31 20:01 UTC, mkurayan commented on contracts/0.8.9/oracle/AccountingOracle.sol
> +        uint256 initialDataOffset = 32;
updated, thanks.

2024-05-31 20:01 UTC, mkurayan commented on contracts/0.8.9/oracle/AccountingOracle.sol
> +        if(data.length < initialDataOffset) {
updated thanks.

2024-05-31 20:01 UTC, mkurayan commented on contracts/0.8.9/oracle/AccountingOracle.sol
>          if (dataHash != procState.dataHash) {
Updated, thanks.

2024-05-31 20:02 UTC, mkurayan commented on contracts/0.8.9/oracle/AccountingOracle.sol
> +        bytes32 nextHash;
updated, thanks.

2024-05-31 20:02 UTC, mkurayan commented on contracts/0.8.9/oracle/AccountingOracle.sol
>              uint256 index;
updated, thanks.

2024-05-31 20:02 UTC, mkurayan commented on contracts/0.8.9/oracle/AccountingOracle.sol
> +            if (!iter.started) {
updated, thanks.

2024-05-31 20:03 UTC, mkurayan commented on contracts/0.8.9/oracle/AccountingOracle.sol
> +            dataOffset: initialDataOffset,
updated, thanks.

2024-05-31 20:06 UTC, mkurayan commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    bytes32 public constant EXITED_VALIDATORS_PER_DAY_LIMIT_MANAGER_ROLE =
After discussion we decided to keep separate roles for each item in order to follow the current sanity checker design where each parameter has it's own role.

2024-06-03 10:54 UTC, avsetsin requested changes

2024-06-03 10:54 UTC, avsetsin commented on contracts/0.4.24/nos/NodeOperatorsRegistry.sol
>          // see `onExitedAndStuckValidatorsCountsUpdated()`
the comment looks outdated

2024-06-03 10:54 UTC, avsetsin commented on contracts/0.4.24/nos/NodeOperatorsRegistry.sol
> +        require(rewardDistributionState == RewardDistributionState.ReadyForDistribution, "Reward distribution is not ready");
Pls, use error key instead of message for consistency with other requires

"Reward distribution is not ready" -> "DISTRIBUTION_NOT_READY"

2024-06-03 10:54 UTC, avsetsin commented on contracts/0.4.24/nos/NodeOperatorsRegistry.sol
> +    // Function to distribute rewards
Consider adding more details and using natspec

2024-06-03 10:54 UTC, avsetsin commented on contracts/0.4.24/nos/NodeOperatorsRegistry.sol
> +    RewardDistributionState public rewardDistributionState = RewardDistributionState.Distributed;
⚠️ adding storage variable here breaks storage layout

2024-06-03 10:54 UTC, avsetsin commented on contracts/0.4.24/nos/NodeOperatorsRegistry.sol
> +    RewardDistributionState public rewardDistributionState = RewardDistributionState.Distributed;
consider using unstructured storage pattern for this

2024-06-03 11:44 UTC, krogla commented on contracts/0.4.24/nos/NodeOperatorsRegistry.sol
> +    RewardDistributionState public rewardDistributionState = RewardDistributionState.Distributed;
also, we should not assign default values to the variables in the implementation, but set them via a call to the `finaliseUpgrade_vXX` method in the proxy

2024-06-03 11:55 UTC, avsetsin requested changes

2024-06-03 11:55 UTC, avsetsin commented on contracts/0.8.9/oracle/AccountingOracle.sol
> +             if (data.extraDataHash == ZERO_HASH) {
```suggestion
            if (data.extraDataHash == ZERO_HASH) {
```

2024-06-03 11:55 UTC, avsetsin commented on contracts/0.8.9/oracle/AccountingOracle.sol
> +             _storageExtraDataProcessingState().value = procState;
```suggestion
            _storageExtraDataProcessingState().value = procState;
```

2024-06-03 11:55 UTC, avsetsin commented on contracts/0.8.9/oracle/AccountingOracle.sol
> +                 ++itemsCount;
```suggestion
                ++itemsCount;
```

2024-06-03 11:55 UTC, avsetsin commented on contracts/0.8.9/oracle/AccountingOracle.sol
> +            // | itemType | 00000000 | moduleId | nodeOpId |
```suggestion
            // | 2 bytes  | 19 bytes | 3 bytes  | 8 bytes  |
            // | itemType | 00000000 | moduleId | nodeOpId |
```

2024-06-03 11:55 UTC, avsetsin commented on contracts/0.8.9/oracle/AccountingOracle.sol
> +                }
let's say we have 1 item with update for NO with id 0.
in this case `nodeOpId` = 0 and `tmpNodeOpId` = 0 which would cause a revert

2024-06-03 11:59 UTC, krogla commented on contracts/0.8.9/oracle/AccountingOracle.sol
> +                }
NO ids starts from 1

2024-06-03 14:02 UTC, mkurayan commented on contracts/0.4.24/nos/NodeOperatorsRegistry.sol
>          // see `onExitedAndStuckValidatorsCountsUpdated()`
Yep, removed, thanks.

2024-06-03 16:16 UTC, avsetsin commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +        keccak256("APPEARED_VALIDATORS_PER_DAY_LIMIT_MANAGER_ROLE");
sanity checker is deployed without a proxy. so it's ok to rename roles, we will have to reassign them (ig they were assigned) anyway

2024-06-03 16:28 UTC, mkurayan commented on contracts/0.4.24/nos/NodeOperatorsRegistry.sol
>          // see `onExitedAndStuckValidatorsCountsUpdated()`
Yep, removed.

2024-06-03 16:28 UTC, avsetsin commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    uint16 appearedValidatorsPerDayLimit;
Sanity checker is deployed without a proxy. So i guess it's ok since this struct is used for storing vars and doesn't look like it uses in external methods

2024-06-03 16:28 UTC, mkurayan commented on contracts/0.4.24/nos/NodeOperatorsRegistry.sol
> +        require(rewardDistributionState == RewardDistributionState.ReadyForDistribution, "Reward distribution is not ready");
Thanks, updated.

2024-06-03 16:30 UTC, mkurayan commented on contracts/0.4.24/nos/NodeOperatorsRegistry.sol
> +    // Function to distribute rewards
Yep I missed this one, description added 👍

2024-06-03 16:33 UTC, mkurayan commented on contracts/0.4.24/nos/NodeOperatorsRegistry.sol
> +    RewardDistributionState public rewardDistributionState = RewardDistributionState.Distributed;
Oh that was a big one, thanks guys!
I moved rewardDistributionState to the end and added `finalizeUpgrade_v3` and `_initialize_v3` for handling things.

2024-06-03 16:35 UTC, mkurayan commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    uint16 appearedValidatorsPerDayLimit;
Yep Sanity checker is deployed without a proxy I oirgot to update this one, after discussion with Mihail we agreed to keep things like this. Thanks.

2024-06-03 16:35 UTC, mkurayan commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    uint256 exitedValidatorsPerDayLimit;
Sanity checker is deployed without a proxy. So it's ok to keep it here.

2024-06-04 07:59 UTC, mkurayan commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    /// @dev Checks against the same limit as used in checkExtraDataItemsCountPerTransaction
Good catch, this phrase is incorrect. 

`checkNodeOperatorsPerExtraDataItemCount` - check the number of node operators reported per extra data item in the accounting oracle report.

`checkExtraDataItemsCountPerTransaction` - check the number of extra data list items per transaction in the accounting oracle report.

Those checks have different purposes and limits.

I will briefly update the function description and remove the incorrect phrase.

2024-06-04 08:06 UTC, mkurayan commented on contracts/0.8.9/oracle/AccountingOracle.sol
> +             if (data.extraDataHash == ZERO_HASH) {
Updated, thanks.

2024-06-04 08:06 UTC, mkurayan commented on contracts/0.8.9/oracle/AccountingOracle.sol
> +                 ++itemsCount;
Updated, thanks.

2024-06-04 08:06 UTC, mkurayan commented on contracts/0.8.9/oracle/AccountingOracle.sol
> +            // | itemType | 00000000 | moduleId | nodeOpId |
Updated, thanks.

2024-06-04 09:40 UTC, avsetsin commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    uint256 exitedValidatorsPerDayLimit;
This particular struct is used as a return value in external `getOracleReportLimits` method. So it's worth caring about backwards compatibility

2024-06-04 09:48 UTC, mkurayan commented on contracts/0.8.9/sanity_checks/OracleReportSanityChecker.sol
> +    uint256 exitedValidatorsPerDayLimit;
Understood, thanks for pointing this one out!

2024-06-04 12:23 UTC, mkurayan commented
merged in https://github.com/lidofinance/core/pull/78

2024-06-04 12:24 UTC, mkurayan commented
merged in https://github.com/lidofinance/core/pull/78

2024-06-04 12:24 UTC, mkurayan commented
merged in https://github.com/lidofinance/core/pull/78

2024-06-04 12:24 UTC, closed without merging